# Generated by Django 3.1 on 2020-10-06 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('strings', models.IntegerField()),
                ('frets', models.IntegerField()),
                ('brand', models.CharField(max_length=100)),
                ('orientation', models.CharField(choices=[('right', 'Right'), ('left', 'Left')], max_length=10)),
                ('price', models.IntegerField()),
                ('discount', models.IntegerField(null=True)),
            ],
        ),
    ]
