# Generated by Django 3.1 on 2020-11-18 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('inst_type', models.CharField(choices=[('acoustic', 'Acoustic'), ('electric', 'Electric'), ('electroacoustic', 'Electro Acoustic'), ('bass', 'Bass'), ('acousticbass', 'Acoustic Bass'), ('ukulele', 'Ukulele')], default='acoustic', max_length=16)),
                ('image', models.ImageField(blank=True, default=None, upload_to='uploads')),
                ('strings', models.IntegerField()),
                ('frets', models.IntegerField()),
                ('brand', models.CharField(max_length=100)),
                ('orientation', models.CharField(choices=[('right', 'Right'), ('left', 'Left')], default='right', max_length=5)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Siteuser',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=22)),
                ('email', models.EmailField(max_length=250)),
                ('password', models.CharField(max_length=250)),
            ],
        ),
    ]
