# Generated by Django 3.1 on 2020-10-06 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_instrument_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrument',
            name='orientation',
            field=models.CharField(choices=[('right', 'Right'), ('left', 'Left')], default='right', max_length=10),
        ),
    ]
