# Generated by Django 3.1 on 2020-10-06 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_auto_20201006_2018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrument',
            name='discount',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='frets',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='image',
            field=models.ImageField(null=True, upload_to='uploads'),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='orientation',
            field=models.CharField(choices=[('right', 'Right'), ('left', 'Left')], default='right', max_length=5),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='strings',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
