# Generated by Django 3.1 on 2020-10-06 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0004_auto_20201006_2024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrument',
            name='discount',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='image',
            field=models.ImageField(blank=True, default=None, upload_to='uploads'),
        ),
    ]
