# Generated by Django 3.1 on 2020-10-06 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0005_auto_20201006_2028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrument',
            name='frets',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='strings',
            field=models.IntegerField(),
        ),
    ]
