# Generated by Django 3.1 on 2020-10-06 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0006_auto_20201006_2135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrument',
            name='discount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
