# Generated by Django 3.1 on 2020-10-06 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0007_auto_20201006_2137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrument',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
