# Generated by Django 3.1 on 2020-10-06 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0009_auto_20201006_2225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrument',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
