# Generated by Django 3.1 on 2020-10-06 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0010_auto_20201006_2226'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrument',
            name='instrument_type',
            field=models.CharField(choices=[('acoustic', 'Acoustic'), ('electric', 'Electric'), ('electroacoustic', 'Electro Acoustic'), ('bass', 'Bass'), ('acousticbass', 'Acoustic Bass'), ('ukulele', 'Ukulele')], default='right', max_length=16),
        ),
    ]
