# Generated by Django 3.1 on 2020-10-06 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0013_auto_20201007_0031'),
    ]

    operations = [
        migrations.RenameField(
            model_name='instrument',
            old_name='instrument_type',
            new_name='inst_type',
        ),
    ]
